language: r
sudo: required
warnings_are_errors: true

apt_packages:
  - libgdal1h
  - libnetcdf-dev
  - libhdf4-alt-dev
  - libhdf5-7
  - libhdf5-dev
  - libhdf5-serial-dev
  - libgdal-dev
  - libproj-dev

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  
after_success:
  - Rscript -e 'covr::codecov()'
 