language: r
sudo: required
warnings_are_errors: true

r_binary_packages:
- rgdal

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  
after_success:
  - Rscript -e 'covr::codecov()'
 