language: r
sudo: required
warnings_are_errors: true

before_install:
  - sudo apt-get install -y libgdal-dev
  - sudo apt-get install -y libproj-dev

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  
after_success:
  - Rscript -e 'covr::codecov()'
 